### ISSUE TITLE
school mail

### ISSUE THREAD

**Issue by amirbios** [BazaarMarkets/Bazaar_Android#11]
hi 
thanks for this project 
how to use school mail register in the app???
please help me 
Thank you.
Email: a1372mir@gmail.com
![photo_2017-01-30_00-01-03](https://cloud.githubusercontent.com/assets/25319470/22407622/48554164-e67f-11e6-98fa-1a2007af8053.jpg)

**Comment by waltonseymour** [comment]
Hi there.

Assuming you were looking for https://divar.ir/
Bazaar is a college marketplace for students so it requires a .edu email

**Comment by amirbios** [comment]
ba salam khedmate doste aziz man ham marketplase mikham baraye yad giri mikhastam esefade konam az projhe ton age momken bashe dar moredesh ye tozih kochik bedin mamnooonam.
hengame sabte namesh mige this in not a valid school email.
in yani chi?
